version: '2.2'

services:

  todolist-client:
    environment: 
      - API_HOST=172.20.20.20
    image: sgtux/todolist-client
    networks:
      todolist-network:
        ipv4_address: 172.20.20.10

  todolist-api:
    environment: 
      - DATABASE_CONNECTION_STRING=Host=172.20.20.30;Port=5432;Pooling=true;Database=site;User Id=site;Password=123
      - JWT_KEY=6e4f26205770397b6b6c2a7952785a5f567e6c375b706231767031507c
    image: sgtux/todolist-api
    networks:
      todolist-network:
        ipv4_address: 172.20.20.20

  todolist-database:
    image: sgtux/todolist-database
    networks:
      todolist-network:
        ipv4_address: 172.20.20.30

  todolist-jenkins:
    image: sgtux/todolist-jenkins:1.0
    networks:
      todolist-network:
        ipv4_address: 172.20.20.40

networks:

  todolist-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.20.0/24