version: '2.2'

services:

  todolist-client:
    environment: 
      - API_HOST=https://172.20.20.20
    image: sgtux/todolist-client
    networks:
      todolist-network:
        ipv4_address: 172.20.20.10

  todolist-api:
    environment: 
      - DATABASE_CONNECTION_STRING=Host=172.20.20.30;Port=5432;Pooling=true;Database=site;User Id=site;Password=123
      - JWT_KEY=6e4f26205770397b6b6c2a7952785a5f567e6c375b706231767031507c
      - TOKEN_EXPIRY_MINUTES=1
      - TZ=America/Sao_Paulo
      - ALLOWED_ORIGINS=http://172.20.20.10;https://172.20.20.10
    image: sgtux/todolist-api
    networks:
      todolist-network:
        ipv4_address: 172.20.20.20

  todolist-database:
    image: sgtux/todolist-database
    networks:
      todolist-network:
        ipv4_address: 172.20.20.30

  todolist-zap:
    image: sgtux/todolist-zap
    networks:
      todolist-network:
        ipv4_address: 172.20.20.40
    volumes:
      - ./zap/files/config-docker.xml:/root/.ZAP_D/config.xml

  # todolist-jenkins:
  #   image: sgtux/todolist-jenkins:1.0
  #   networks:
  #     todolist-network:
  #       ipv4_address: 172.20.20.40

  # todolist-jenkins:
  #   image: sgtux/secdevops-octopus:latest
  #   networks:
  #     todolist-network:
  #       ipv4_address: 172.20.20.50

networks:

  todolist-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.20.0/24